---
title: "Map"
author: "Chuhan Liu"
date: "2/14/2022"
output: html_document
---

```{r}
# collecting the data
library(rio)

linkCSV='https://github.com/chuhanl/Deliverable-3/raw/main/wwmarstatus.csv'
mydata=read.csv(linkCSV)
str(mydata)
```

```{r}
boxplot(mydata[,c('Divrate','divtomarRatio')])
```

```{r}
# standardization
mydata$DIV_S=as.vector(scale(mydata$Divrate))
mydata$RATIO_S=as.vector(scale(mydata$divtomarRatio))
```

```{r}
# cluster the data using pam
set.seed(123)

library(cluster)
vars=c('DIV_S','RATIO_S')

distMatrix=cluster::daisy(mydata[,vars])
          
res.pam=cluster::pam(x=distMatrix,
                     k = 3,
                     cluster.only = F)

mydata$cluster=as.factor(res.pam$clustering)
```

```{r}
theVars=c('DIV_S','RATIO_S','cluster')
aggregate(.~cluster,
          data=mydata[,theVars],
          FUN=median)

mydata$cluster=factor(mydata$cluster,
                           levels=c(1,2,3),
                           labels=c("low","mid","high"), 
                           ordered=T)
```

```{r}
# open the map and add the data to the map
linkMap="https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/worldMap.geojson" 

library(sf)
mapWorld=read_sf(linkMap)

mapWorldVars=merge(mapWorld,
                   mydata, 
                   by='ISO3')
```

1. Base layer:
```{r}
library(ggplot2)

base=ggplot(data=mapWorld) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()

base
```

2. Data layer:
```{r}
clusterMap= base + geom_sf(data=mapWorldVars,
                           aes(fill=cluster),
                           color=NA)

theLegTitle="World_Order_of_Divorce_Rate\n(grey is missing)"

clusterMap+ scale_fill_brewer(palette ='YlOrBr',
                              name=theLegTitle)
```

